from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

from atomref_proatoms.dataio.datasets import (
    AUGMENTED_DYALL_AV4Z,
    PRIMARY_DYALL_V4Z,
    PRIMARY_X2C_QZVPALL,
    SUPPLEMENTED_X2C_QZVPALL_S,
    load_profile_dataset_config,
    multiwfn_rad_allowed_for_dataset,
    multiwfn_wfn_allowed_for_dataset,
)
from atomref_proatoms.dataio.paths import STATES_FILE
from atomref_proatoms.exporters.multiwfn_artifacts import (
    MULTIWFN_ARTIFACT_MANIFEST_SCHEMA_VERSION,
    build_multiwfn_artifact_jobs,
    format_multiwfn_artifact_plan,
    manifest_payload,
    multiwfn_artifact_plan_summary,
)
from atomref_proatoms.exporters.multiwfn_rad import (
    MULTIWFN_ATMRAD_GRID_BOHR,
    write_multiwfn_rad_file,
)
from atomref_proatoms.states.state_tables import load_atom_states

ROOT = Path(__file__).resolve().parents[2]


def test_dataset_multiwfn_artifact_policy_is_explicit() -> None:
    config = load_profile_dataset_config()
    assert config.scope(PRIMARY_X2C_QZVPALL).multiwfn_rad == "all_states"
    assert config.scope(PRIMARY_X2C_QZVPALL).multiwfn_wfn == "neutral_atoms"
    assert config.scope(PRIMARY_DYALL_V4Z).multiwfn_rad == "all_states"
    assert config.scope(PRIMARY_DYALL_V4Z).multiwfn_wfn == "none"
    assert config.scope(SUPPLEMENTED_X2C_QZVPALL_S).multiwfn_rad == "none"
    assert config.scope(AUGMENTED_DYALL_AV4Z).multiwfn_wfn == "none"
    assert multiwfn_rad_allowed_for_dataset(PRIMARY_X2C_QZVPALL, charge=-1)
    assert multiwfn_rad_allowed_for_dataset(PRIMARY_DYALL_V4Z, charge=3)
    assert multiwfn_wfn_allowed_for_dataset(PRIMARY_X2C_QZVPALL, charge=0)
    assert not multiwfn_wfn_allowed_for_dataset(PRIMARY_X2C_QZVPALL, charge=-1)
    assert not multiwfn_rad_allowed_for_dataset(SUPPLEMENTED_X2C_QZVPALL_S, charge=0)


def test_multiwfn_artifact_plan_counts() -> None:
    states = load_atom_states(STATES_FILE)
    jobs = build_multiwfn_artifact_jobs(states)
    summary = multiwfn_artifact_plan_summary(jobs)
    formatted = format_multiwfn_artifact_plan(jobs)

    assert summary["rad_file_count"] == 430 + 501
    assert summary["wfn_file_count"] == 86
    assert summary["job_count"] == 430 + 501
    assert summary["by_dataset"][PRIMARY_X2C_QZVPALL] == {"rad": 430, "wfn": 86, "total": 430}
    assert summary["by_dataset"][PRIMARY_DYALL_V4Z] == {"rad": 501, "wfn": 0, "total": 501}
    assert SUPPLEMENTED_X2C_QZVPALL_S not in summary["by_dataset"]
    assert ".rad files: 931" in formatted
    assert ".wfn files: 86" in formatted


def test_export_multiwfn_artifacts_dry_run_does_not_require_pyscf_or_write(tmp_path: Path) -> None:
    result = subprocess.run(
        [
            sys.executable,
            "scripts/export_multiwfn_artifacts.py",
            "--dataset",
            PRIMARY_X2C_QZVPALL,
            "--state",
            "H_q0_mult2_nist",
            "--format",
            "all",
            "--output-root",
            str(tmp_path / "multiwfn"),
            "--dry-run",
            "--show-jobs",
        ],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )

    assert "Multiwfn export jobs: 1" in result.stdout
    assert ".rad files: 1" in result.stdout
    assert ".wfn files: 1" in result.stdout
    assert "H_0.rad" in result.stdout
    assert "H .wfn" in result.stdout
    assert ".rad SCF-density evaluation: fixed_axis_spherical_scf" in result.stdout
    assert "Required local SCF artifact directories for .rad/.wfn export:" in result.stdout
    assert "local-data/scf/" in result.stdout
    assert "Required profile CSVs" not in result.stdout
    assert "Dry run completed before Multiwfn artifact export" in result.stdout
    assert not (tmp_path / "multiwfn").exists()


def test_export_multiwfn_artifacts_defaults_to_rad(tmp_path: Path) -> None:
    result = subprocess.run(
        [
            sys.executable,
            "scripts/export_multiwfn_artifacts.py",
            "--dataset",
            PRIMARY_X2C_QZVPALL,
            "--state",
            "H_q0_mult2_nist",
            "--output-root",
            str(tmp_path / "multiwfn"),
            "--dry-run",
        ],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )

    assert ".rad files: 1" in result.stdout
    assert ".wfn files: 0" in result.stdout
    assert "fixed_axis_spherical_scf" in result.stdout
    assert "H_0.rad" not in result.stdout  # hidden unless --show-jobs is requested


def test_multiwfn_artifact_readme_is_tracked_data_contract() -> None:
    readme = ROOT / "data" / "multiwfn_artifacts" / "README.md"
    text = readme.read_text(encoding="utf-8")

    assert "Multiwfn interoperability data" in text
    assert "not generated by" in text
    assert "interpolating the committed `profiles.csv`" in text



def test_manifest_payload_normalizes_legacy_file_alias() -> None:
    payload = manifest_payload(
        output_root=ROOT / "data" / "multiwfn_artifacts",
        profile_data_version="2.0.0",
        config_path=ROOT / "data" / "profile_datasets.yaml",
        jobs=[],
        files=[
            {
                "format": "rad",
                "path": "data/multiwfn_artifacts/rad/example/H_0.rad",
                "file": "/tmp/nonportable/H_0.rad",
            }
        ],
    )

    record = payload["files"][0]
    assert record["path"] == "data/multiwfn_artifacts/rad/example/H_0.rad"
    assert record["file"] == record["path"]


def test_committed_multiwfn_manifest_uses_repo_relative_paths() -> None:
    manifest_path = ROOT / "data" / "multiwfn_artifacts" / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    assert manifest["output_root"] == "data/multiwfn_artifacts"
    assert manifest["files"]
    for record in manifest["files"]:
        path_text = str(record["path"])
        assert not Path(path_text).is_absolute()
        assert record.get("file") == path_text
        assert not Path(str(record["source_scf_checkpoint"])).is_absolute()
        assert not Path(str(record["source_scf_npz"])).is_absolute()
        assert not Path(str(record["source_scf_metadata"])).is_absolute()


def test_check_multiwfn_artifacts_validates_scf_sourced_rad_manifest(tmp_path: Path) -> None:
    out = tmp_path / "multiwfn"
    rad_path = out / "rad" / PRIMARY_X2C_QZVPALL / "H_0.rad"
    info = write_multiwfn_rad_file(
        rad_path, MULTIWFN_ATMRAD_GRID_BOHR, 0.1 * MULTIWFN_ATMRAD_GRID_BOHR
    )
    manifest = {
        "schema_version": MULTIWFN_ARTIFACT_MANIFEST_SCHEMA_VERSION,
        "profile_data_version": "2.0.0",
        "config": "data/profile_datasets.yaml",
        "output_root": str(out),
        "generated_by": "tests",
        "summary": {"job_count": 1, "rad_file_count": 1, "wfn_file_count": 0},
        "files": [
            {
                "format": "rad",
                "dataset_id": PRIMARY_X2C_QZVPALL,
                "state_id": "H_q0_mult2_nist",
                "symbol": "H",
                "charge": 0,
                "path": str(rad_path),
                "source": "scf_density_evaluation",
                "source_scf_checkpoint": "local-data/scf/test/scf.chk",
                "source_scf_npz": "local-data/scf/test/scf.npz",
                "source_scf_metadata": "local-data/scf/test/scf.json",
                "rad_evaluation": "fixed_axis_spherical_scf",
                "rad_angular_points": 1,
                **info,
            }
        ],
    }
    (out / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")

    result = subprocess.run(
        [
            sys.executable,
            "scripts/check_multiwfn_artifacts.py",
            "--artifact-root",
            str(out),
            "--require-generated",
        ],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )

    assert "OK: checked 1 Multiwfn interoperability files" in result.stdout
    assert ".rad files: 1" in result.stdout
    assert ".wfn files: 0" in result.stdout


def test_check_multiwfn_artifacts_rejects_profile_interpolated_rad_manifest(tmp_path: Path) -> None:
    out = tmp_path / "multiwfn"
    rad_path = out / "rad" / PRIMARY_X2C_QZVPALL / "H_0.rad"
    info = write_multiwfn_rad_file(
        rad_path, MULTIWFN_ATMRAD_GRID_BOHR, 0.1 * MULTIWFN_ATMRAD_GRID_BOHR
    )
    manifest = {
        "schema_version": MULTIWFN_ARTIFACT_MANIFEST_SCHEMA_VERSION,
        "profile_data_version": "2.0.0",
        "config": "data/profile_datasets.yaml",
        "output_root": str(out),
        "generated_by": "tests",
        "summary": {"job_count": 1, "rad_file_count": 1, "wfn_file_count": 0},
        "files": [
            {
                "format": "rad",
                "dataset_id": PRIMARY_X2C_QZVPALL,
                "state_id": "H_q0_mult2_nist",
                "symbol": "H",
                "charge": 0,
                "path": str(rad_path),
                "source": "profile_interpolation",
                **info,
            }
        ],
    }
    (out / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")

    result = subprocess.run(
        [
            sys.executable,
            "scripts/check_multiwfn_artifacts.py",
            "--artifact-root",
            str(out),
            "--require-generated",
        ],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 1
    assert "generated from local SCF artifacts" in result.stderr
